services:
  app:
    image: node
    depends_on:
      - db
    command: 
      - node app.js
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  db:
    image: sunny
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=post18288
    volumes:
      - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata:
